cxf.path: /soap-api
spring:
  spelgates:
    restEndpointGate: "!#request.getBusinessData().getFirstName().startsWith('A')"
    soapEndpointGate: "!#request.getBusinessData().getFirstName().startsWith('B')"
