openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example Service OpenAPI Spec
  license:
    name: MIT
# [paths] section is not used for generation yet
paths:
  /get-data:
    post:
      summary: Get FICO score
      responses:
        '200':
          description: FICO Score
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        default:
          description: An error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseTechData"
components:
  schemas:
    Request:
      type: object
      properties:
        techData:
            $ref: "#/components/schemas/RequestTechData"
        businessData:
            $ref: "#/components/schemas/RequestBusinessData"
      required:
        - techData
        - businessData
    Response:
      type: object
      properties:
        techData:
            $ref: "#/components/schemas/ResponseTechData"
        businessData:
            $ref: "#/components/schemas/ResponseBusinessData"
      required:
        - techData
    RequestTechData:
      type: object
      properties:
        correlationId:
          type: string
      required:
        - correlationId
    ResponseTechData:
        type: object
        properties:
          responseCode:
            type: string
          errorDescription:
            type: string
          correlationId:
            type: string
        required:
          - correlationId
          - responseCode
    RequestBusinessData:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        gender:
          type: string
          enum: [MALE, FEMALE, OTHER]
      required:
        - firstName
        - lastName
    ResponseBusinessData:
      type: object
      properties:
        ficoScore:
          type: number
          format: double
        lastUpdated:
          type: string
          format: date-time
        footnotes:
          type: array
          items:
            type: string
      required:
        - ficoScore